// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZKcdq_6eTybl6_WrRALsLLhDLMWQWg7Y',
    appId: '1:959933684970:web:75eeba4e1bad0001438b93',
    messagingSenderId: '959933684970',
    projectId: 'notizenn-ad09f',
    authDomain: 'notizenn-ad09f.firebaseapp.com',
    storageBucket: 'notizenn-ad09f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2JWzB6YFwnFQeDNf2jwIdnAHye6VJCI',
    appId: '1:959933684970:android:5890915a17a3f18b438b93',
    messagingSenderId: '959933684970',
    projectId: 'notizenn-ad09f',
    storageBucket: 'notizenn-ad09f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XgX0oGYKJ7dLYL_cwWMJiiuur5m2_Ok',
    appId: '1:959933684970:ios:d12a331b97939c02438b93',
    messagingSenderId: '959933684970',
    projectId: 'notizenn-ad09f',
    storageBucket: 'notizenn-ad09f.appspot.com',
    iosBundleId: 'com.example.notizenabgabe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XgX0oGYKJ7dLYL_cwWMJiiuur5m2_Ok',
    appId: '1:959933684970:ios:c457cbd830f15f7a438b93',
    messagingSenderId: '959933684970',
    projectId: 'notizenn-ad09f',
    storageBucket: 'notizenn-ad09f.appspot.com',
    iosBundleId: 'com.example.notizenabgabe.RunnerTests',
  );
}
